docker-build:
  # Official docker image.
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    -  env
    -  docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - cd app/
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - proxmox-home


