version: '3'
services:
  mongodb:
    image: mongo:4.0.4
    container_name: mongodb
    volumes:
      - ${PWD}/mongo-volume/mongo-data:/data/db
      - ${PWD}/mongo-volume/mongo-config:/data/configdb
      - ${PWD}/mongo-volume/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
        - 27017:27017
    command: mongod
    env_file:
      - .mongo_env

  app:
    image: devopstom/web-site:latest
    container_name: app
    ports:
        - 8080
    env_file:
      - .app_env

  nginx:
    image: nginx:stable
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

