version: '3'
services:
  mongodb:
    image: mongo:4.0.4
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secretx
    volumes:
      - /Users/tomaszsuchorowski/GIT/opstom-flask/mongodb-storage/data:/data/db
      - /Users/tomaszsuchorowski/GIT/opstom-flask/mongodb-storage/config:/data/configdb
    ports:
        - 27017:27017
    command: mongod

  opstom-flask:
    image: opstom-flask:latest
    container_name: opstom-flask
    ports:
        - 5001:5001
  
  nginx:
    image: nginx:stable
    container_name: nginx
    ports:
      - 80:80
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

