version: '3'
services:
  mongodb:
    image: mongo:4.0.4
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: data_admin
      MONGO_INITDB_ROOT_PASSWORD: secretx
    volumes:
      - ${HOME}/opstom-flask/mongodb-storage/data:/data/db
      - ${HOME}/opstom-flask/mongodb-storage/config:/data/configdb
    ports:
        - 27017:27017
    command: mongod

  app:
    image: eu.gcr.io/big-blend-273414/devopstom/app:latest
    container_name: app
    ports:
        - 8080
    env_file:
      - .app_env

  nginx:
    image: nginx:stable
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

