version: '3'
services:
  mongodb:
    image: mongo:4.0.4
    container_name: mongodb
    volumes:
      - ${HOME}/opstom-flask/mongodb-storage/data:/data/db
      - ${HOME}/opstom-flask/mongodb-storage/config:/data/configdb
    ports:
        - 27017:27017
    command: mongod
    env_file:
      - .mongo_env

  app:
    image: registry.digitalocean.com/devopstom/devopstom-app:latest
    container_name: app
    ports:
        - 8080
    env_file:
      - .app_env

  nginx:
    image: nginx:stable
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

