resources:
  - app-deploy.yml
images:
- name: registry.gitlab.com/dev-ops-tom/devopstom:v0.1.5
  newName: registry.gitlab.com/dev-ops-tom/devopstom
  newTag: v0.1.14

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: web-site
  path: patch_name.yml
