apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
  namespace: nginx
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/probe: "true"
        prometheus.io/port: "80"
        prometheus.io/path: "/metrics"
      labels:
        app: nginx
    spec:
      nodeSelector:
        dedicated: "web-pool"
      tolerations:
      - key: "dedicated"
        operator: "Exists"
      containers:
      - name: nginx
        image: nginx:stable
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        resources:
            requests:
              memory: "512m"
              cpu: "100m"
            limits:
              memory: "1G"
              cpu: "200m"
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: nginx-conf
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
            readOnly: true
          # - name: nginx-ssl
          #   mountPath: /etc/nginx/ssl/devopstom.crt
          #   subPath: tls.crt
          # - name: nginx-ssl
          #   mountPath: /etc/nginx/ssl/devopstom.key
          #   subPath: tls.key
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
      # - name: nginx-ssl
      #   secret:
      #     secretName: devopstom.ssl
