---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: nginx
data:
  nginx.conf: |-
    user www-data;
    worker_processes auto;
    pid /run/nginx.pid;

    events {
        worker_connections 1024;
        use epoll;
        multi_accept on;
    }

    http {
        access_log /dev/stdout;
        error_log /dev/stdout;

        sendfile            on;
        tcp_nopush          on;
        tcp_nodelay         on;
        keepalive_timeout   65;
        types_hash_max_size 2048;

        include             /etc/nginx/mime.types;
        default_type        application/octet-stream;

        upstream app-ingress {
          ip_hash;
          zone app 64k;
          server app-ingress.ingress:80  max_fails=0 fail_timeout=1s;
        }

        server {
            listen       80 default_server;
            server_name  www.devopstom.com.pl;
            root         /var/www/html;

            location / {
                # include uwsgi_params;
                # uwsgi_param X-Forwarded-For $proxy_add_x_forwarded_for;
                # uwsgi_param X-Forwarded-Proto $http_x_forwarded_proto;
                # uwsgi_pass app;

                proxy_set_header                    X-Real-IP $remote_addr;
                proxy_set_header                    X-Forwarded-For $remote_addr;
                proxy_set_header                    Host $http_host;
                proxy_pass_header                   Set-Cookie;
                proxy_redirect                      off;

                proxy_pass http://app-ingress;
            }
            location /favicon.ico {
              alias /usr/share/nginx/html/favicon.ico;
            }
        }
    }

