---
# Source: etcd-operator/templates/operator-service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-etcd-op-etcd-operator-etcd-operator
  labels:
    chart: "etcd-operator-0.11.2"
    app: etcd-operator
    heritage: Helm
    release: my-etcd-op
imagePullSecrets: 
  []
---
# Source: etcd-operator/templates/operator-cluster-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: my-etcd-op-etcd-operator-etcd-operator
  labels:
    chart: "etcd-operator-0.11.2"
    app: etcd-operator
    heritage: Helm
    release: my-etcd-op
rules:
- apiGroups:
  - etcd.database.coreos.com
  resources:
  - etcdclusters
  - etcdbackups
  - etcdrestores
  verbs:
  - "*"
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
---
# Source: etcd-operator/templates/operator-clusterrole-binding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: my-etcd-op-etcd-operator-etcd-operator
  labels:
    chart: "etcd-operator-0.11.2"
    app: etcd-operator
    heritage: Helm
    release: my-etcd-op
subjects:
- kind: ServiceAccount
  name: my-etcd-op-etcd-operator-etcd-operator
  namespace: app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: my-etcd-op-etcd-operator-etcd-operator
---
# Source: etcd-operator/templates/restore-operator-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: etcd-restore-operator
  labels:
    chart: "etcd-operator-0.11.2"
    app: etcd-restore-operator
    heritage: Helm
    release: my-etcd-op
spec:
  ports:
  - protocol: TCP
    name: http-etcd-restore-port
    port: 19999
  selector:
    app: etcd-restore-operator
    release: my-etcd-op
---
# Source: etcd-operator/templates/backup-operator-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-etcd-op-etcd-operator-etcd-backup-operator
  labels:
    chart: "etcd-operator-0.11.2"
    app: etcd-backup-operator
    heritage: Helm
    release: my-etcd-op
spec:
  selector:
    matchLabels:
      app: my-etcd-op-etcd-operator-etcd-backup-operator
      release: my-etcd-op
  replicas: 1
  template:
    metadata:
      name: my-etcd-op-etcd-operator-etcd-backup-operator
      labels:
        app: my-etcd-op-etcd-operator-etcd-backup-operator
        release: my-etcd-op
    spec:
      serviceAccountName: my-etcd-op-etcd-operator-etcd-operator
      containers:
      - name: etcd-backup-operator
        image: "quay.io/coreos/etcd-operator:v0.9.4"
        imagePullPolicy: Always
        command:
        - etcd-backup-operator
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
---
# Source: etcd-operator/templates/operator-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-etcd-op-etcd-operator-etcd-operator
  labels:
    chart: "etcd-operator-0.11.2"
    app: etcd-operator
    heritage: Helm
    release: my-etcd-op
spec:
  selector:
    matchLabels:
      app: my-etcd-op-etcd-operator-etcd-operator
      release: my-etcd-op
  replicas: 1
  template:
    metadata:
      name: my-etcd-op-etcd-operator-etcd-operator
      labels:
        app: my-etcd-op-etcd-operator-etcd-operator
        release: my-etcd-op
      annotations: 
        null
    spec:
      serviceAccountName: my-etcd-op-etcd-operator-etcd-operator
      containers:
      - name: my-etcd-op-etcd-operator-etcd-operator
        image: "quay.io/coreos/etcd-operator:v0.9.4"
        imagePullPolicy: Always
        command:
        - etcd-operator
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
---
# Source: etcd-operator/templates/restore-operator-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-etcd-op-etcd-operator-etcd-restore-operator
  labels:
    chart: "etcd-operator-0.11.2"
    app: etcd-restore-operator
    heritage: Helm
    release: my-etcd-op
spec:
  selector:
    matchLabels:
      app: etcd-restore-operator
      release: my-etcd-op
  replicas: 1
  template:
    metadata:
      name: my-etcd-op-etcd-operator-etcd-restore-operator
      labels:
        app: etcd-restore-operator
        release: my-etcd-op
    spec:
      serviceAccountName: my-etcd-op-etcd-operator-etcd-operator
      containers:
      - name: etcd-restore-operator
        image: "quay.io/coreos/etcd-operator:v0.9.4"
        imagePullPolicy: Always
        ports:
        - containerPort: 19999
        command:
        - etcd-restore-operator
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: SERVICE_ADDR
          value: "etcd-restore-operator:19999"
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
---
# Source: etcd-operator/templates/crds.yaml
# Synced with https://github.com/coreos/etcd-operator/blob/master/pkg/util/k8sutil/crd.go
