{
 "title": "Kubernetes Cluster (Prometheus)",
 "description": "Summary metrics about containers running on Kubernetes nodes.\r\n\r\nDashboard was taken from here.  This version does not reqiure you to\r\nsetup the Kubernetes-app plugin. (https://github.com/grafana/kubernetes-app)\r\n\r\nUse this Helm chart to launch Grafana into a Kubernetes cluster.  It will include this dashboard and many more dashboards to give you visibility into the Kubernetes Cluster. (https://github.com/sekka1/cloud-public/tree/master/kubernetes/pods/grafana-helm)",
 "tags": [
  "kubernetes",
  "kubernetes-app"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "node", "query": ".*" },
   { "name": "namespace", "query": ".*" }
  ]
 },
 "panels": [
  { "title": "Cluster Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster Pod Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_info{node=~\"$node\"}) / sum(kube_node_status_allocatable_pods{node=~\".*\"})"
    }
   ]
  },
  {
   "title": "Cluster CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{node=~\"$node\"}) / sum(kube_node_status_allocatable_cpu_cores{node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Cluster Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{node=~\"$node\"}) / sum(kube_node_status_allocatable_memory_bytes{node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Cluster Disk Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum (node_filesystem_size{nodename=~\"$node\"}) - sum (node_filesystem_free{nodename=~\"$node\"})) / sum (node_filesystem_size{nodename=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Cluster Pod Capacity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "pods" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_pods{node=~\"$node\"})",
     "legendFormat": "allocatable"
    },
    {
     "expr": "sum(kube_node_status_capacity_pods{node=~\"$node\"})",
     "legendFormat": "capacity"
    },
    {
     "expr": "sum(kube_pod_info{node=~\"$node\"})",
     "legendFormat": "requested"
    }
   ]
  },
  {
   "title": "Cluster CPU Capacity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity_cpu_cores{node=~\"$node\"})",
     "legendFormat": "allocatable"
    },
    {
     "expr": "sum(kube_node_status_allocatable_cpu_cores{node=~\"$node\"})",
     "legendFormat": "capacity"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{node=~\"$node\"})",
     "legendFormat": "requested"
    }
   ]
  },
  {
   "title": "Cluster Mem Capacity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_memory_bytes{node=~\"$node\"})",
     "legendFormat": "allocatable"
    },
    {
     "expr": "sum(kube_node_status_capacity_memory_bytes{node=~\"$node\"})",
     "legendFormat": "capacity"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{node=~\"$node\"})",
     "legendFormat": "requested"
    }
   ]
  },
  {
   "title": "Cluster Disk Capacity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_filesystem_size{nodename=~\"$node\"}) - sum(node_filesystem_free{nodename=~\"$node\"})",
     "legendFormat": "usage"
    },
    {
     "expr": "sum(node_filesystem_size{nodename=~\"$node\"})",
     "legendFormat": "limit"
    }
   ]
  },
  { "title": "Deployments", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Deployment Replicas - Up To Date",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{namespace=~\"$namespace\"}",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  {
   "title": "Deployment Replicas",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Deployment Replicas - Updated",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_updated{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Deployment Replicas - Unavailable",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=~\"$namespace\"})"
    }
   ]
  },
  { "title": "Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Number Of Nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 17 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_node_info{node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Nodes Out of Disk",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"OutOfDisk\", node=~\"$node\", status=\"true\"})"
    }
   ]
  },
  {
   "title": "Nodes Unavailable",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_spec_unschedulable{node=~\"$node\"})"
    }
   ]
  },
  { "title": "Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Pods Running",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Running\"})"
    }
   ]
  },
  {
   "title": "Pods Pending",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Pending\"})"
    }
   ]
  },
  {
   "title": "Pods Failed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Failed\"})"
    }
   ]
  },
  {
   "title": "Pods Succeeded",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Succeeded\"})"
    }
   ]
  },
  {
   "title": "Pods Unknown",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Unknown\"})"
    }
   ]
  },
  { "title": "Containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Containers Running",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 28 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Containers Waiting",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 28 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Containers Terminated",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 28 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_terminated{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Containers Restarts (Last 30 Minutes)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 28 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(delta(kube_pod_container_status_restarts{namespace=\"kube-system\"}[30m]))"
    }
   ]
  },
  {
   "title": "CPU Cores Requested by Containers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 31 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=~\"$namespace\", node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Memory Requested By Containers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 31 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=~\"$namespace\", node=~\"$node\"})"
    }
   ]
  },
  { "title": "Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Jobs Succeeded",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 35 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_job_status_succeeded{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Jobs Succeeded",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 35 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_job_status_active{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Jobs Failed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 35 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_job_status_failed{namespace=~\"$namespace\"})"
    }
   ]
  }
 ]
}
{
 "title": "NGINX Ingress controller",
 "description": "Fork of https://github.com/kubernetes/ingress-nginx/tree/master/deploy/grafana/dashboards",
 "tags": [ "nginx" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(nginx_ingress_controller_config_hash, controller_namespace)"
   },
   {
    "name": "controller_class",
    "label": "Controller Class",
    "query": "label_values(nginx_ingress_controller_config_hash{namespace=~\"$namespace\"}, controller_class) "
   },
   {
    "name": "controller",
    "label": "Controller",
    "query": "label_values(nginx_ingress_controller_config_hash{namespace=~\"$namespace\",controller_class=~\"$controller_class\"}, controller_pod) "
   },
   {
    "name": "ingress",
    "label": "Ingress",
    "query": "label_values(nginx_ingress_controller_requests{namespace=~\"$namespace\",controller_class=~\"$controller_class\",controller=~\"$controller\"}, ingress) "
   }
  ]
 },
 "panels": [
  {
   "title": "Controller Request Volume",
   "type": "singlestat",
   "format": "ops",
   "valueName": "avg",
   "targets": [
    {
     "expr": "round(sum(irate(nginx_ingress_controller_requests{controller_pod=~\"$controller\",controller_class=~\"$controller_class\",namespace=~\"$namespace\"}[2m])), 0.001)"
    }
   ]
  },
  {
   "title": "Controller Connections",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(avg_over_time(nginx_ingress_controller_nginx_process_connections{controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\"}[2m]))"
    }
   ]
  },
  {
   "title": "Controller Success Rate (non-4|5xx responses)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{controller_pod=~\"$controller\",controller_class=~\"$controller_class\",namespace=~\"$namespace\",status=~\"[1,2,3,404].*\"}[2m])) / sum(rate(nginx_ingress_controller_requests{controller_pod=~\"$controller\",controller_class=~\"$controller_class\",namespace=~\"$namespace\"}[2m]))"
    }
   ]
  },
  {
   "title": "Config Reloads",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(nginx_ingress_controller_success{controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Last Config Failed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(nginx_ingress_controller_config_last_reload_successful{controller_pod=~\"$controller\",controller_namespace=~\"$namespace\"} == 0)"
    }
   ]
  },
  {
   "title": "Ingress Request Per Minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(irate(nginx_ingress_controller_requests{controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\",ingress=~\"$ingress\"}[5m])) by (ingress)",
     "legendFormat": "{{ ingress }}"
    }
   ]
  },
  {
   "title": "Ingress Success Rate (1xx, 2xx, 3xx, 404)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{controller_pod=~\"$controller\",controller_class=~\"$controller_class\",namespace=~\"$namespace\",ingress=~\"$ingress\",status=~\"[1,2,3,404].*\"}[5m])) by (ingress) / sum(rate(nginx_ingress_controller_requests{controller_pod=~\"$controller\",controller_class=~\"$controller_class\",namespace=~\"$namespace\",ingress=~\"$ingress\"}[5m])) by (ingress) < 1",
     "legendFormat": "{{ ingress }}"
    }
   ]
  },
  {
   "title": "Ingress Percentile Response Times and Transfer Rates",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=~\".*production.*nginx.*\", ingress!=\"\",controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\",ingress=~\"$ingress\"}[2m])) by (le, ingress))",
     "legendFormat": "{{ ingress }}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=~\".*production.*nginx.*\", ingress!=\"\",controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\",ingress=~\"$ingress\"}[2m])) by (le, ingress))",
     "legendFormat": "{{ ingress }}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=~\".*production.*nginx.*\", ingress!=\"\",controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\",ingress=~\"$ingress\"}[2m])) by (le, ingress))",
     "legendFormat": "{{ destination_service }}"
    }
   ]
  },
  {
   "title": "Ingress Certificate Expiry",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "avg(nginx_ingress_controller_ssl_expire_time_seconds{kubernetes_pod_name=~\"$controller\",namespace=~\"$namespace\",ingress=~\"$ingress\"}) by (host) - time()",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Network I/O pressure",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (irate (nginx_ingress_controller_request_size_sum{controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\"}[2m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum (irate (nginx_ingress_controller_response_size_sum{controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\"}[2m]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Average Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(nginx_ingress_controller_nginx_process_resident_memory_bytes{controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\"}) ",
     "legendFormat": "nginx"
    }
   ]
  },
  {
   "title": "Average CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (nginx_ingress_controller_nginx_process_cpu_seconds_total{controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\"}[2m])) ",
     "legendFormat": "nginx"
    }
   ]
  }
 ]
}