apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app-ingress
  namespace: ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-ingress
  template:
    metadata:
      labels:
        app: app-ingress
      annotations:
        prometheus.io/port: "10254"
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: nginx-ingress
      nodeSelector:
        dedicated: web-pool
      tolerations:
      - key: "dedicated"
        operator: "Exists"
      containers:
      - image: quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.20.0
        imagePullPolicy: IfNotPresent
        name: nginx-ingress-container
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        args:
          - /nginx-ingress-controller
          - --publish-service=$(POD_NAMESPACE)/app-ingress
          - --ingress-class=app-ingress
          - --configmap=$(POD_NAMESPACE)/app-ingress-config
          #- --v=5
        securityContext:
          capabilities:
            drop:
              - ALL
            add:
              - NET_BIND_SERVICE
            # www-data -> 33
          runAsUser: 33
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-ingress-config
  namespace: ingress
  labels:
    app.kubernetes.io/name: app-ingress
    app.kubernetes.io/part-of: app-ingress
data:
  proxy-buffer-size: "16k"
  large-client-header-buffers: "4 16k"
  client-body-buffer-size: "32k"
  worker-processes: "8"
  proxy-body-size: "0"
  disable-access-log: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: app-ingress
  namespace: ingress
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  selector:
    app: app-ingress

